django/d20/surveys/urls.py
from django.urls import path
from . import views

app_name = 'surveys'

urlpatterns = [
    path('', views.index, name='list'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/delete/', views.delete, name='delete'),
    path('<int:question_id>/edit/', views.edit, name='edit'),
    path('<int:question_id>/update/', views.update, name='update'),
    path('<int:question_id>/choices/create/', views.choice_create, name='choice_create'),
    path('<int:question_id>/choices/<int:choice_id>/delete/', views.choice_delete, name='choice_delete'),

]

django/d20/workshop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include 
# from 앱이름 import views

urlpatterns = [
    path('surveys/', include('surveys.urls')),
    path('admin/', admin.site.urls),
#     path('new/', views.new),
]

django/d20/surveys/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=100)  

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.CharField(max_length=1000)
    votes = models.IntegerField()
    

django/d20/surveys/views.py
from django.shortcuts import render, redirect
from .models import Question, Choice

# Create your views here.
def new(request):
    return render(request, 'new.html')


def create(request):
    title = request.POST.get('title')  # POST는 요청 방식
    question = Question(title=title)
    question.save()
    return redirect('surveys:detail', question.pk)
    

def detail(request, question_id):    
    question = Question.objects.get(pk=question_id) #id도 그냥 이름이다
    return render(request, 'detail.html', {'question':question})
    
def index(request):
    question = Question.objects.all()
    return render(request, 'index.html', {'question':question})
    
def delete(request, question_id):
    # 삭제하는 코드
    question = Question.objects.get(pk=question_id)
    question.delete()
    return redirect("surveys:list")
    
def edit(request, question_id):
    question = Question.objects.get(pk=question_id)
    return render(request, 'edit.html', {'question':question})

def update(request, question_id):
    # 수정하는 코드
    question = Question.objects.get(pk=question_id)
    question.title = request.POST.get('title')
    question.save()
    return redirect('surveys:detail', question.pk)

def choice_create(request, question_id):
    # 댓글을 달 게시물
    question = Question.objects.get(pk=question_id)
    
    # form에서 넘어온 댓글 내용
    content = request.POST.get('content')
    votes = request.POST.get('votes')
    
    # 댓글 생성 및 저장
    choice = Choice(question=question, content=content, votes= votes)
    choice.save()
    return redirect('surveys:detail', question.pk)
    
def choice_delete(request, question_id, choice_id):
    choice = Choice.objects.get(pk=choice_id)
    choice.delete()
    return redirect('surveys:detail', question_id)
    
    

django/d20/surveys/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Survey App</h1>
    <h2>title : {{ question.title }}</h2>
    <a href="{% url 'surveys:list' %}">List</a>
    <a href="{% url 'surveys:edit' question.pk %}">edit</a>
    <a href="{% url 'surveys:delete' question.pk %}">Delete</a>
    
    
     <hr>
    
    <form action='{% url "surveys:choice_create" question.pk %}' method='post'>
        {% csrf_token %}
        content(내용) : <input type="text" name="content"/>
        votes(투표수) : <input type="numbet" name="votes"/>
        <input type="submit" value="Submit"/>
    </form>
    
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.content }} : {{ choice.votes }}표<a href="{% url 'surveys:choice_delete' question.pk choice.pk %}">Delete</a> </li>
        {% endfor %}
    </ul>
    
</body>
</html>

django/d20/surveys/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Survey Edit</h1>
    <form action="{% url 'surveys:update' question.pk %}" method="post">
        {% csrf_token %}
        <input type="text" name="title" value="{{ question.title }}"/>     
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>

django/d20/surveys/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>회식 메뉴 추천</h1>
    <a href="{% url 'surveys:new'%}">New</a>
    <ul>
    {% for student in students %}        
        <li> <a href="{% url 'surveys:detail' question.pk %}">{{ question.title }} </li></a>
    {% endfor %}  
    </ul>
    
</body>
</html>

django/d20/surveys/templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'surveys:create' %}" method="post"> 
        {% csrf_token %}
        <input type="text" name="title"/>      
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>